apiVersion: v1
kind: ReplicationController
metadata:
  name: world-v2
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    version: 2
    app: helloworld
    tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        version: 2
        app: helloworld
        tier: world
    spec:
      containers:
        image: world
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 5502
